# Generated by Django 5.0.4 on 2024-05-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VacationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('vacation_date_start', models.DateField()),
                ('vacation_date_end', models.DateField()),
                ('vacation_file', models.FileField(upload_to='vacation_file_scan/%Y/%m/%d')),
            ],
        ),
    ]
