# Generated by Django 5.0.4 on 2024-05-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VacationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('vacation_date_start', models.CharField(max_length=128)),
                ('vacation_date_end', models.CharField(max_length=128)),
                ('vacation_file', models.FileField(upload_to='vacation_file_scan/%Y/%m/%d')),
                ('status_confirm', models.CharField(choices=[('На согласовании', 'На согласовании'), ('Согласовано', 'Согласовано'), ('Отказ', 'Отказ')], default=('На согласовании', 'На согласовании'), max_length=128)),
                ('job', models.CharField(choices=[('Job example', 'Job example'), ('Job example_2', 'Job example_2')], max_length=128)),
            ],
        ),
    ]
