# Generated by Django 5.0.4 on 2024-05-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationmodel',
            name='status_confirm',
            field=models.BooleanField(null=True),
        ),
    ]
