# Generated by Django 5.0.4 on 2024-05-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationmodel',
            name='vacation_date_end',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='vacationmodel',
            name='vacation_date_start',
            field=models.CharField(max_length=127),
        ),
    ]
