# Generated by Django 5.0.4 on 2024-05-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationmodel',
            name='job',
            field=models.CharField(choices=[('Job example', 'Job example'), ('Job example_2', 'Job example_2')], default='Не назначен', max_length=128),
        ),
        migrations.AlterField(
            model_name='vacationmodel',
            name='status_confirm',
            field=models.CharField(choices=[('in_process', 'На согласовании'), ('approved', 'Согласовано'), ('declined', 'Отказ')], default=('in_process', 'На согласовании'), max_length=128),
        ),
    ]
