# Generated by Django 5.0.4 on 2024-06-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationmodel',
            name='vacation_date_end',
            field=models.DateField(max_length=128),
        ),
        migrations.AlterField(
            model_name='vacationmodel',
            name='vacation_date_start',
            field=models.DateField(max_length=128),
        ),
    ]
