# Generated by Django 5.0.4 on 2024-05-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation_app', '0002_alter_vacationmodel_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationmodel',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
