# Generated by Django 5.0.4 on 2024-05-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation_app', '0003_vacationmodel_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationmodel',
            name='status_confirm',
            field=models.CharField(choices=[('На согласовании', 'На согласовании'), ('Согласовано', 'Согласовано'), ('Отказ', 'Отказ')], default=('На согласовании', 'На согласовании'), max_length=128),
        ),
    ]
