# Generated by Django 5.0.4 on 2024-05-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation_app', '0004_alter_vacationmodel_status_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationmodel',
            name='job',
            field=models.CharField(choices=[('Не назначен', 'Не назнчаен'), ('Job example', 'Job example'), ('Job example_2', 'Job example_2')], default='Не назначен', max_length=128),
        ),
    ]
