# Generated by Django 5.0.4 on 2024-06-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0012_alter_vacancyrequestmodel_resume_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacationmodel',
            name='boss_name',
        ),
    ]
