# Generated by Django 5.0.4 on 2024-06-01 20:04

import about_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutemployeemodel',
            name='photo',
            field=models.ImageField(upload_to=about_app.models.upload_to),
        ),
    ]
