# Generated by Django 5.0.4 on 2024-06-02 15:24

import news_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_alter_newsmodel_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsmodel',
            old_name='photo',
            new_name='title_photo',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='context_photo',
            field=models.ImageField(blank=True, null=True, upload_to=news_app.models.upload_to),
        ),
    ]
