# Generated by Django 5.0.4 on 2024-06-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_rename_photo_newsmodel_title_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='context_photo',
        ),
    ]
