# Generated by Django 5.0.4 on 2024-06-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_remove_newsmodel_context_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsmodel',
            old_name='title_photo',
            new_name='photo',
        ),
    ]
